// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hexfind_cpp
IntegerVector hexfind_cpp(RawVector x, RawVector block);
RcppExport SEXP _hexutils_hexfind_cpp(SEXP xSEXP, SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< RawVector >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(hexfind_cpp(x, block));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexutils_hexfind_cpp", (DL_FUNC) &_hexutils_hexfind_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
